# Generated by Django 3.2.7 on 2022-09-03 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=255)),
                ('aciklama', models.TextField(blank=True, null=True)),
                ('yaratilma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('güncellenme_tarihi', models.DateTimeField(auto_now=True)),
                ('yayın_tarihi', models.DateTimeField()),
                ('blog_sahibi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_sahibi', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
